// Code generated by protoc-gen-go. DO NOT EDIT.
// source: workerpb/worker.proto

package workerpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TaskRequest struct {
	Node                 string   `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Condition            string   `protobuf:"bytes,2,opt,name=condition,proto3" json:"condition,omitempty"`
	Action               string   `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Params               string   `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskRequest) Reset()         { *m = TaskRequest{} }
func (m *TaskRequest) String() string { return proto.CompactTextString(m) }
func (*TaskRequest) ProtoMessage()    {}
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5e70f8309ff9e66, []int{0}
}

func (m *TaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskRequest.Unmarshal(m, b)
}
func (m *TaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskRequest.Marshal(b, m, deterministic)
}
func (m *TaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskRequest.Merge(m, src)
}
func (m *TaskRequest) XXX_Size() int {
	return xxx_messageInfo_TaskRequest.Size(m)
}
func (m *TaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskRequest proto.InternalMessageInfo

func (m *TaskRequest) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *TaskRequest) GetCondition() string {
	if m != nil {
		return m.Condition
	}
	return ""
}

func (m *TaskRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *TaskRequest) GetParams() string {
	if m != nil {
		return m.Params
	}
	return ""
}

type TaskAck struct {
	Condition            string   `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskAck) Reset()         { *m = TaskAck{} }
func (m *TaskAck) String() string { return proto.CompactTextString(m) }
func (*TaskAck) ProtoMessage()    {}
func (*TaskAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5e70f8309ff9e66, []int{1}
}

func (m *TaskAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskAck.Unmarshal(m, b)
}
func (m *TaskAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskAck.Marshal(b, m, deterministic)
}
func (m *TaskAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskAck.Merge(m, src)
}
func (m *TaskAck) XXX_Size() int {
	return xxx_messageInfo_TaskAck.Size(m)
}
func (m *TaskAck) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskAck.DiscardUnknown(m)
}

var xxx_messageInfo_TaskAck proto.InternalMessageInfo

func (m *TaskAck) GetCondition() string {
	if m != nil {
		return m.Condition
	}
	return ""
}

type TaskResult struct {
	Node                 string               `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Condition            string               `protobuf:"bytes,2,opt,name=condition,proto3" json:"condition,omitempty"`
	Action               string               `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Worker               string               `protobuf:"bytes,4,opt,name=worker,proto3" json:"worker,omitempty"`
	Success              bool                 `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TaskResult) Reset()         { *m = TaskResult{} }
func (m *TaskResult) String() string { return proto.CompactTextString(m) }
func (*TaskResult) ProtoMessage()    {}
func (*TaskResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5e70f8309ff9e66, []int{2}
}

func (m *TaskResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskResult.Unmarshal(m, b)
}
func (m *TaskResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskResult.Marshal(b, m, deterministic)
}
func (m *TaskResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskResult.Merge(m, src)
}
func (m *TaskResult) XXX_Size() int {
	return xxx_messageInfo_TaskResult.Size(m)
}
func (m *TaskResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskResult.DiscardUnknown(m)
}

var xxx_messageInfo_TaskResult proto.InternalMessageInfo

func (m *TaskResult) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *TaskResult) GetCondition() string {
	if m != nil {
		return m.Condition
	}
	return ""
}

func (m *TaskResult) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *TaskResult) GetWorker() string {
	if m != nil {
		return m.Worker
	}
	return ""
}

func (m *TaskResult) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *TaskResult) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func init() {
	proto.RegisterType((*TaskRequest)(nil), "worker.TaskRequest")
	proto.RegisterType((*TaskAck)(nil), "worker.TaskAck")
	proto.RegisterType((*TaskResult)(nil), "worker.TaskResult")
}

func init() { proto.RegisterFile("workerpb/worker.proto", fileDescriptor_e5e70f8309ff9e66) }

var fileDescriptor_e5e70f8309ff9e66 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x41, 0x4f, 0xc2, 0x40,
	0x10, 0x85, 0xb3, 0x8a, 0x05, 0x06, 0x13, 0x93, 0x31, 0x9a, 0x0d, 0x31, 0x91, 0x70, 0x91, 0x83,
	0x29, 0x09, 0x5c, 0x4c, 0x3c, 0xe1, 0xcd, 0x6b, 0xc5, 0x8b, 0xb7, 0x65, 0x3b, 0x92, 0xa6, 0xb4,
	0x5b, 0xbb, 0x5b, 0xfc, 0x7f, 0xfe, 0x32, 0xd3, 0x1d, 0x56, 0x40, 0xaf, 0xde, 0xe6, 0xbd, 0x37,
	0x79, 0x9d, 0x7c, 0x5d, 0xb8, 0xfa, 0x34, 0x75, 0x4e, 0x75, 0xb5, 0x9a, 0xf2, 0x10, 0x57, 0xb5,
	0x71, 0x06, 0x23, 0x56, 0xc3, 0xdb, 0xb5, 0x31, 0xeb, 0x0d, 0x4d, 0xbd, 0xbb, 0x6a, 0xde, 0xa7,
	0x2e, 0x2b, 0xc8, 0x3a, 0x55, 0x54, 0xbc, 0x38, 0x36, 0x30, 0x58, 0x2a, 0x9b, 0x27, 0xf4, 0xd1,
	0x90, 0x75, 0x88, 0xd0, 0x29, 0x4d, 0x4a, 0x52, 0x8c, 0xc4, 0xa4, 0x9f, 0xf8, 0x19, 0x6f, 0xa0,
	0xaf, 0x4d, 0x99, 0x66, 0x2e, 0x33, 0xa5, 0x3c, 0xf1, 0xc1, 0xde, 0xc0, 0x6b, 0x88, 0x94, 0xf6,
	0xd1, 0xa9, 0x8f, 0x76, 0xaa, 0xf5, 0x2b, 0x55, 0xab, 0xc2, 0xca, 0x0e, 0xfb, 0xac, 0xc6, 0x77,
	0xd0, 0x6d, 0x3f, 0xb8, 0xd0, 0xf9, 0x71, 0xb1, 0xf8, 0x55, 0x3c, 0xfe, 0x12, 0x00, 0x7c, 0x9a,
	0x6d, 0x36, 0xff, 0x7c, 0x19, 0xd3, 0x09, 0x97, 0xb1, 0x42, 0x09, 0x5d, 0xdb, 0x68, 0x4d, 0xd6,
	0xca, 0xb3, 0x91, 0x98, 0xf4, 0x92, 0x20, 0xf1, 0x01, 0xfa, 0x3f, 0xdc, 0x64, 0x34, 0x12, 0x93,
	0xc1, 0x6c, 0x18, 0x33, 0xd9, 0x38, 0x90, 0x8d, 0x97, 0x61, 0x23, 0xd9, 0x2f, 0xcf, 0x1e, 0x19,
	0xef, 0x0b, 0xd5, 0xdb, 0x4c, 0x13, 0xde, 0x43, 0xa7, 0x95, 0x78, 0x19, 0xef, 0xfe, 0xd6, 0x01,
	0xfb, 0xe1, 0xc5, 0xa1, 0xb9, 0xd0, 0xf9, 0xec, 0x19, 0x90, 0x73, 0x4d, 0xd9, 0x96, 0x42, 0xc7,
	0x1c, 0xce, 0x19, 0xc9, 0x6b, 0x95, 0x2a, 0x47, 0x88, 0xc7, 0x5d, 0x6d, 0xf2, 0xa7, 0xea, 0x09,
	0xde, 0x7a, 0xe1, 0xa1, 0xac, 0x22, 0x7f, 0xf2, 0xfc, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xc6, 0x01,
	0xc9, 0x8f, 0x3b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TaskServiceClient interface {
	Task(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskAck, error)
}

type taskServiceClient struct {
	cc *grpc.ClientConn
}

func NewTaskServiceClient(cc *grpc.ClientConn) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) Task(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskAck, error) {
	out := new(TaskAck)
	err := c.cc.Invoke(ctx, "/worker.TaskService/Task", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServiceServer is the server API for TaskService service.
type TaskServiceServer interface {
	Task(context.Context, *TaskRequest) (*TaskAck, error)
}

// UnimplementedTaskServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTaskServiceServer struct {
}

func (*UnimplementedTaskServiceServer) Task(ctx context.Context, req *TaskRequest) (*TaskAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Task not implemented")
}

func RegisterTaskServiceServer(s *grpc.Server, srv TaskServiceServer) {
	s.RegisterService(&_TaskService_serviceDesc, srv)
}

func _TaskService_Task_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).Task(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/worker.TaskService/Task",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).Task(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TaskService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "worker.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Task",
			Handler:    _TaskService_Task_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workerpb/worker.proto",
}

// TaskReceiveServiceClient is the client API for TaskReceiveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TaskReceiveServiceClient interface {
	ResultUpdate(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*TaskAck, error)
}

type taskReceiveServiceClient struct {
	cc *grpc.ClientConn
}

func NewTaskReceiveServiceClient(cc *grpc.ClientConn) TaskReceiveServiceClient {
	return &taskReceiveServiceClient{cc}
}

func (c *taskReceiveServiceClient) ResultUpdate(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*TaskAck, error) {
	out := new(TaskAck)
	err := c.cc.Invoke(ctx, "/worker.TaskReceiveService/ResultUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskReceiveServiceServer is the server API for TaskReceiveService service.
type TaskReceiveServiceServer interface {
	ResultUpdate(context.Context, *TaskResult) (*TaskAck, error)
}

// UnimplementedTaskReceiveServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTaskReceiveServiceServer struct {
}

func (*UnimplementedTaskReceiveServiceServer) ResultUpdate(ctx context.Context, req *TaskResult) (*TaskAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResultUpdate not implemented")
}

func RegisterTaskReceiveServiceServer(s *grpc.Server, srv TaskReceiveServiceServer) {
	s.RegisterService(&_TaskReceiveService_serviceDesc, srv)
}

func _TaskReceiveService_ResultUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskReceiveServiceServer).ResultUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/worker.TaskReceiveService/ResultUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskReceiveServiceServer).ResultUpdate(ctx, req.(*TaskResult))
	}
	return interceptor(ctx, in, info, handler)
}

var _TaskReceiveService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "worker.TaskReceiveService",
	HandlerType: (*TaskReceiveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResultUpdate",
			Handler:    _TaskReceiveService_ResultUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workerpb/worker.proto",
}
