[general]
log_file = "/var/log/service/node-alert-worker.log"
received_metrics_file = "/var/metrics/received_metrics.log"
results_metrics_file = "/var/metrics/results_metrics.log"
cache_expire_interval = "10h"
max_parallel_tasks = 3
namespace = "node-alert-worker"

# This section comprises option for running scripts including ansible plays
[scripts]
dir = "/etc/ansible-repo"

[server]
address = "0.0.0.0"
port  =  "9191"
health_check_port = "8080"

[responder]
namespace = "node-alert-responder"
port = "9090"

[certs]
cert_file = "/box/etc/pki/node-alert-worker.crt"
key_file = "/box/etc/pki/node-alert-worker.key"
ca_cert_file = "/box/etc/pki/node-alert-worker.pem"