[general]
log_file = "/var/log/service/node-alert-worker.log"
#log_file = "/tmp/node-alert-worker.log"
cache_expire_interval = "10h"
max_parallel_tasks = 3
namespace = "node-alert-worker"

[server]
address = "0.0.0.0"
port  =  "9191"
health_check_port = "8080"

[responder]
namespace = "node-alert-responder"
#address = "10.228.149.225"
port = "9090"

[certs]
cert_file = "/box/etc/pki/node-alert-worker.crt"
key_file = "/box/etc/pki/node-alert-worker.key"
ca_cert_file = "/box/etc/pki/node-alert-worker.pem"